allow_anonymous false
listener 1883

listener 9001
protocol websockets
cafile /etc/letsencrypt/live/memo-pazirik.ir/chain.pem
certfile /etc/letsencrypt/live/memo-pazirik.ir/fullchain.pem
keyfile /etc/letsencrypt/live/memo-pazirik.ir/privkey.pem

listener 8883
cafile /etc/letsencrypt/live/memo-pazirik.ir/chain.pem
certfile /etc/letsencrypt/live/memo-pazirik.ir/fullchain.pem
keyfile /etc/letsencrypt/live/memo-pazirik.ir/privkey.pem

persistence true
password_file /mosquitto/config/pwfile
persistence_file mosquitto.db
persistence_location /mosquitto/data/