# version: "3.8"
networks:
  laravel:
    name: laravel
    driver: bridge
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - php
      - postgres
      - pgadmin
      - neo4j
      - redis
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  # mysql:
  #   platform: "linux/x86_64"
  #   image: "mysql:8.0"
  #   container_name: mysql
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "secret"
  #     MYSQL_USER: "laravel"
  #     MYSQL_PASSWORD: "secret"
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "no"
  #     MYSQL_DATABASE: "laraveldb"
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   networks:
  #     - laravel

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_USER: root
  #     PMA_PASSWORD: secret
  #     PMA_ARBITRARY: 1
  #   restart: always
  #   volumes:
  #     - "./pmadata/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - laravel
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smarthome
      POSTGRES_USER: smarthome
      POSTGRES_PASSWORD: smarthome_password
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      # POSTGRES_USER: smarthome
      # POSTGRES_PASSWORD: smarthome_password
      PGADMIN_DEFAULT_EMAIL: mrzamanian77@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Mrz@12345
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - laravel

  neo4j:
    image: neo4j:5
    container_name: neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/topaz123
      # فعال کردن پلاگین‌ها (از جمله GDS)
      NEO4J_PLUGINS: '["graph-data-science", "apoc"]'
      # اجازه استفاده از بعضی قابلیت‌های APOC (اختیاری ولی معمولاً لازم)
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
    ports:
      - "7474:7474"   # Browser / UI
      - "7687:7687"   # Bolt (برای Laravel)
    volumes:
      - ./docker/neo4j/data:/data
      - ./docker/neo4j/logs:/logs
      - ./docker/neo4j/plugins:/plugins
    networks:
      - laravel


  composer:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["composer"]
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - laravel
  npm:
    image: node:22.12-alpine3.20
    container_name: npm
    ports:
      - 5173:5173
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel

  phpunit:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: phpunit
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/vendor/bin/phpunit"]
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.15
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    security_opt:
      - no-new-privileges:true
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: scheduler
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan", "schedule:work"]
    networks:
      - laravel

