# version: "3.8"
networks:
  laravel:
    name: laravel
    driver: bridge

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - php
      - mysql
      - phpmyadmin
      - redis
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  mysql:
    platform: "linux/x86_64"
    image: "mysql:8.0"
    container_name: mysql
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "laravel"
      MYSQL_PASSWORD: "secret"
      MYSQL_ALLOW_EMPTY_PASSWORD: no
      MYSQL_DATABASE: "laraveldb"
    volumes:
      - "./mysql:/var/lib/mysql/"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
      PMA_ARBITRARY: 1
    restart: always
    volumes:
      - "./pmadata:/etc/phpmyadmin/config.user.inc.php"
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - laravel
  composer:
    image: composer:2.8.3
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php","artisan"]
    networks:
      - laravel
  npm:
    image: node:22.12-alpine3.20
    container_name: npm
    ports:
      - 5173:5173
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel
  
  phpunit:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: phpunit
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/vendor/bin/phpunit"]
    networks:
      - laravel
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel