version: "3.8"

networks:
  laravel:
    name: laravel

services:
  nginx:
    container_name: nginx
    # image: nginx:stable-alpine
    build: 
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  php:
    image: php:7.4.12-fpm-alpine
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MySQL_DATABASE: laraveldb
      MYAQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel
