server {
    listen 80;
    server_name memo-pazirik.ir www.memo-pazirik.ir;
    return 301 https://$host$request_uri;  # ???????? HTTP ?? HTTPS
}

server {
    listen 443 ssl;
    server_name memo-pazirik.ir www.memo-pazirik.ir;

    ssl_certificate /etc/letsencrypt/live/memo-pazirik.ir/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/memo-pazirik.ir/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

    root /var/www/html/public;  # ???? ????? Laravel
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;  # ??? ?????? ????? PHP ??? ???? 9000???
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}